package Program5;

import java.awt.Font;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author ahimes1
 */
public class PurchaseFrame extends javax.swing.JFrame {
    
    private PurchaseData dataObject;
    private int pistAmount;
    private String radioChoice;
    
    /**
     * Creates new form PurchaseFrame
     */
    public PurchaseFrame() {
        initComponents();
        dataObject = new PurchaseData();
        pistAmount = 0;
        radioChoice = "Mystery Cereal";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTSummary = new javax.swing.JTextArea();
        jBSummary = new javax.swing.JButton();
        jBSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCFruits = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFAdjective2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBTotal = new javax.swing.JButton();
        jLTotal = new javax.swing.JLabel();
        jSPistachios = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jLPAmount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFAdjective1 = new javax.swing.JTextField();
        jRCorn = new javax.swing.JRadioButton();
        jRRaisin = new javax.swing.JRadioButton();
        jRMystery = new javax.swing.JRadioButton();
        jRClam = new javax.swing.JRadioButton();
        jRVeg = new javax.swing.JRadioButton();
        jRChicken = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCheckChips = new javax.swing.JCheckBox();
        jCheckCandy = new javax.swing.JCheckBox();
        jCheckSoda = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTSummary.setColumns(20);
        jTSummary.setRows(5);
        jTSummary.setToolTipText("Purchase summary listed here");
        jScrollPane1.setViewportView(jTSummary);

        jBSummary.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBSummary.setText("Summary");
        jBSummary.setToolTipText("Click to see total summary");
        jBSummary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBSummaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBSummaryMouseExited(evt);
            }
        });
        jBSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSummaryActionPerformed(evt);
            }
        });

        jBSave.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBSave.setText("Save");
        jBSave.setToolTipText("Click to create file of order summary");
        jBSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBSaveMouseExited(evt);
            }
        });
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Marion", 0, 18)); // NOI18N
        jLabel1.setText("ONLINE GROCERY STORE");

        jCFruits.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"apple", "pear", "orange", "peach"}));
        jCFruits.setSelectedItem(jCFruits);
        jCFruits.setToolTipText("A fruit must be selected!");
        jCFruits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFruitsActionPerformed(evt);
            }
        });

        jLabel2.setText("You must select ONE fruit.");

        jLabel3.setText("Write one or two adjectives below.");

        jTFAdjective2.setText("");
        jTFAdjective2.setToolTipText("Enter an adjective.");

        jLabel4.setText("$1.00");

        jBTotal.setBackground(new java.awt.Color(0, 204, 0));
        jBTotal.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jBTotal.setForeground(new java.awt.Color(204, 204, 0));
        jBTotal.setText("DISPLAY TOTAL");
        jBTotal.setToolTipText("Click to see total.");
        jBTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTotalActionPerformed(evt);
            }
        });

        jLTotal.setToolTipText("Click the Display Total button!");

        jSPistachios.setMajorTickSpacing(5);
        jSPistachios.setMaximum(50);
        jSPistachios.setMinorTickSpacing(1);
        jSPistachios.setPaintLabels(true);
        jSPistachios.setPaintTicks(true);
        jSPistachios.setToolTipText("Range between 0 and 50 pistachios.");
        jSPistachios.setValue(0);
        jSPistachios.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSPistachiosStateChanged(evt);
            }
        });

        jLabel5.setText("Pistachios");

        jLPAmount.setText("0 x $.05");

        jLabel6.setText("- $3.89");

        jLabel7.setText("- $2.35");

        jLabel8.setText("- FREE??");

        jTFAdjective1.setText("");
        jTFAdjective1.setToolTipText("Enter an adjective.");

        buttonGroup1.add(jRCorn);
        jRCorn.setText("Corn Flakes");
        jRCorn.setToolTipText("Flakes of Corn");
        jRCorn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRCornActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRRaisin);
        jRRaisin.setText("Raisin Bran");
        jRRaisin.setToolTipText("Bran of Raisin");
        jRRaisin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRRaisinActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRMystery);
        jRMystery.setSelected(true);
        jRMystery.setText("Mystery Cereal");
        jRMystery.setToolTipText("Cereal of Mystery");
        jRMystery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRMysteryActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRClam);
        jRClam.setText("Clam Chowder");
        jRClam.setToolTipText("A drastic soup.");
        jRClam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRClamActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRVeg);
        jRVeg.setSelected(true);
        jRVeg.setText("Vegetable Beef");
        jRVeg.setToolTipText("We're all out!!");
        jRVeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRVegActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRChicken);
        jRChicken.setText("Chicken Soup");
        jRChicken.setToolTipText("May cause tiredness.");
        jRChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRChickenActionPerformed(evt);
            }
        });

        jLabel9.setText("- $3.95");

        jLabel10.setText("- SOLD OUT!");

        jLabel11.setText("- $4.11");

        jLabel12.setFont(new java.awt.Font("Wide Latin", 2, 10)); // NOI18N
        jLabel12.setText("CEREAL AISLE");

        jLabel13.setFont(new java.awt.Font("Wide Latin", 2, 10)); // NOI18N
        jLabel13.setText("SOUP AISLE");

        jCheckChips.setText("Chips");
        jCheckChips.setToolTipText("Crunch");
        jCheckChips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckChipsActionPerformed(evt);
            }
        });

        jCheckCandy.setText("Candy");
        jCheckCandy.setToolTipText("Chomp");
        jCheckCandy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckCandyActionPerformed(evt);
            }
        });

        jCheckSoda.setText("Soda");
        jCheckSoda.setToolTipText("Glug");
        jCheckSoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckSodaActionPerformed(evt);
            }
        });

        jLabel14.setText("- $.99");

        jLabel15.setText("- $1.09");

        jLabel16.setText("- $2.15");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCFruits, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRCorn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRMystery)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRRaisin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRChicken)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRClam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRVeg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addComponent(jLabel13)))
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTFAdjective2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTFAdjective1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jBTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLPAmount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSPistachios, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckSoda)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckCandy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jBSave))
                                    .addComponent(jBSummary, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(104, 104, 104))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckChips)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCFruits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLPAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSPistachios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFAdjective1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTFAdjective2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jRCorn)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRRaisin)
                                        .addComponent(jLabel7))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRMystery)
                                        .addComponent(jLabel8)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jRClam)
                                                .addComponent(jLabel9))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jRVeg)
                                                .addComponent(jLabel10))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jRChicken)
                                                .addComponent(jLabel11)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jBSummary)
                                            .addGap(26, 26, 26)
                                            .addComponent(jBSave)
                                            .addGap(18, 18, 18)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckChips)
                            .addComponent(jLabel14))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckCandy)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckSoda)
                            .addComponent(jLabel16))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBTotal)
                        .addGap(18, 18, 18)
                        .addComponent(jLTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSummaryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSummaryMouseEntered
        jBSummary.setFont(new Font("Arial", Font.PLAIN, 24));
    }//GEN-LAST:event_jBSummaryMouseEntered

    private void jBSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSaveMouseEntered
        jBSave.setFont(new Font("Arial", Font.PLAIN, 24));
    }//GEN-LAST:event_jBSaveMouseEntered

    private void jBSummaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSummaryMouseExited
        jBSummary.setFont(new Font("Arial", Font.PLAIN, 12));
    }//GEN-LAST:event_jBSummaryMouseExited

    private void jBSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSaveMouseExited
        jBSave.setFont(new Font("Arial", Font.PLAIN, 12));
    }//GEN-LAST:event_jBSaveMouseExited

    private void jBSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSummaryActionPerformed
        dataObject.setTextField1(jTFAdjective1.getText());
        dataObject.setTextField2(jTFAdjective2.getText());
        
        jTSummary.setText(dataObject.getSummary());
    }//GEN-LAST:event_jBSummaryActionPerformed

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        saveFile();
    }//GEN-LAST:event_jBSaveActionPerformed

    private void jCFruitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFruitsActionPerformed
        dataObject.setCombo((String)jCFruits.getSelectedItem());
    }//GEN-LAST:event_jCFruitsActionPerformed

    private void jBTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTotalActionPerformed

        jLTotal.setText(dataObject.getTotal());
    }//GEN-LAST:event_jBTotalActionPerformed

    private void jSPistachiosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSPistachiosStateChanged
        pistAmount = jSPistachios.getValue();
        jLPAmount.setText(pistAmount + " x $.05");
        dataObject.setSlider(pistAmount);
    }//GEN-LAST:event_jSPistachiosStateChanged

    private void jRCornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRCornActionPerformed
        dataObject.setRadio1(jRCorn.getText());
    }//GEN-LAST:event_jRCornActionPerformed

    private void jRRaisinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRRaisinActionPerformed
        dataObject.setRadio1(jRRaisin.getText());
    }//GEN-LAST:event_jRRaisinActionPerformed

    private void jRMysteryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRMysteryActionPerformed
        dataObject.setRadio1(jRMystery.getText());
    }//GEN-LAST:event_jRMysteryActionPerformed

    private void jRClamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRClamActionPerformed
        dataObject.setRadio2(jRClam.getText());
    }//GEN-LAST:event_jRClamActionPerformed

    private void jRVegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRVegActionPerformed
        dataObject.setRadio2(jRVeg.getText());
    }//GEN-LAST:event_jRVegActionPerformed

    private void jRChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRChickenActionPerformed
        dataObject.setRadio2(jRChicken.getText());
    }//GEN-LAST:event_jRChickenActionPerformed

    private void jCheckChipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckChipsActionPerformed
        String chips;
        if (jCheckChips.isSelected())
            chips = jCheckChips.getText();
        else
            chips = "";
        
        dataObject.setCheck1(chips);
    }//GEN-LAST:event_jCheckChipsActionPerformed

    private void jCheckCandyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckCandyActionPerformed
        String candy;
        if (jCheckCandy.isSelected())
            candy = jCheckCandy.getText();
        else
            candy = "";
        
        dataObject.setCheck2(candy);
    }//GEN-LAST:event_jCheckCandyActionPerformed

    private void jCheckSodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckSodaActionPerformed
        String soda;
        if (jCheckSoda.isSelected())
            soda = jCheckSoda.getText();
        else
            soda = "";
        
        dataObject.setCheck3(soda);
    }//GEN-LAST:event_jCheckSodaActionPerformed
  
        
    
    private void saveFile(){
        JFileChooser fileChooser = new JFileChooser();
        int choice = fileChooser.showSaveDialog(this);
        if(choice == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            dataObject.writeFile(file);
        }
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PurchaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PurchaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PurchaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PurchaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PurchaseFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBSave;
    private javax.swing.JButton jBSummary;
    private javax.swing.JButton jBTotal;
    private javax.swing.JComboBox jCFruits;
    private javax.swing.JCheckBox jCheckCandy;
    private javax.swing.JCheckBox jCheckChips;
    private javax.swing.JCheckBox jCheckSoda;
    private javax.swing.JLabel jLPAmount;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRChicken;
    private javax.swing.JRadioButton jRClam;
    private javax.swing.JRadioButton jRCorn;
    private javax.swing.JRadioButton jRMystery;
    private javax.swing.JRadioButton jRRaisin;
    private javax.swing.JRadioButton jRVeg;
    private javax.swing.JSlider jSPistachios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFAdjective1;
    private javax.swing.JTextField jTFAdjective2;
    private javax.swing.JTextArea jTSummary;
    // End of variables declaration//GEN-END:variables
}
