//Alan Himes
//ahimes1@cnm.edu
//Program 9 Enigma with Polymorphism
//CIS2235
//File: MainP9.java, EnigmaFrame.java, EnigmaClass.java, EnigmaInterface.java, PrimeShift.java, Qwerty.java, Alternate.java

package Program9;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ahimes1
 */
public class EnigmaFrame extends javax.swing.JFrame {
    private EnigmaClass[] e;
    private PrimeShift pse;
    private Qwerty qe;
    private Alternate ae;
    private int index;
    
    /**
     * Creates new form EnigmaFrame
     */
    public EnigmaFrame() {
        initComponents();
        
        pse = new PrimeShift();
        qe = new Qwerty();
        ae = new Alternate();
        
        e = new EnigmaClass[3];
        e[0] = pse;
        e[1] = qe;
        e[2] = ae;
        
        index = 0;//used for selecting which EnigmaClass element.
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBRandom = new javax.swing.JButton();
        jBEncode = new javax.swing.JButton();
        jLEncodedMessage = new javax.swing.JLabel();
        jBSave = new javax.swing.JButton();
        jTFMessage = new javax.swing.JTextField();
        jTFKey = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRBPrime = new javax.swing.JRadioButton();
        jRBQwerty = new javax.swing.JRadioButton();
        jRBAlternate = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLEncodedMessage2 = new javax.swing.JLabel();
        jBOpen = new javax.swing.JButton();
        jBDecode = new javax.swing.JButton();
        jLDecodedMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Write a message to be encoded:");

        jLabel2.setText("Enter a number from 1 to 50 for the key (or just click the Random button)");

        jBRandom.setText("Random");
        jBRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRandomActionPerformed(evt);
            }
        });

        jBEncode.setText("Encode Message");
        jBEncode.setEnabled(false);
        jBEncode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEncodeActionPerformed(evt);
            }
        });

        jLEncodedMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jBSave.setText("Save");
        jBSave.setEnabled(false);
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        jTFMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFMessageKeyReleased(evt);
            }
        });

        jTFKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFKeyKeyReleased(evt);
            }
        });

        jLabel3.setText("Choose an encoding method.");

        buttonGroup1.add(jRBPrime);
        jRBPrime.setSelected(true);
        jRBPrime.setText("Prime Shift");
        jRBPrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPrimeActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBQwerty);
        jRBQwerty.setText("Qwerty");
        jRBQwerty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBQwertyActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBAlternate);
        jRBAlternate.setText("Alternate");
        jRBAlternate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAlternateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBSave))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFMessage)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBEncode)
                        .addGap(202, 202, 202))
                    .addComponent(jLEncodedMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTFKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBRandom))
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRBPrime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRBQwerty)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRBAlternate)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBPrime)
                    .addComponent(jRBQwerty)
                    .addComponent(jRBAlternate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRandom)
                    .addComponent(jTFKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEncode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLEncodedMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSave)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Encode", jPanel1);

        jLabel4.setText("Encoded message:");

        jLEncodedMessage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEncodedMessage2.setText("No encoded message. Enter a message to encode in the encode tab or open a file.");

        jBOpen.setText("Open");
        jBOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOpenActionPerformed(evt);
            }
        });

        jBDecode.setText("Decode message");
        jBDecode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDecodeActionPerformed(evt);
            }
        });

        jLDecodedMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBOpen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jBDecode)
                        .addGap(207, 207, 207))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLEncodedMessage2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLDecodedMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLEncodedMessage2)
                .addGap(85, 85, 85)
                .addComponent(jBDecode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLDecodedMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jBOpen)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Decode", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFMessageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFMessageKeyReleased
        /*The encode and save buttons will not be available unless something's 
        typed in the text fields.*/
        messageCheck();
    }//GEN-LAST:event_jTFMessageKeyReleased

    private void jTFKeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFKeyKeyReleased
        messageCheck();
    }//GEN-LAST:event_jTFKeyKeyReleased

    private void jBEncodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEncodeActionPerformed
        try {
            e[index].setMessage(jTFMessage.getText(), Integer.parseInt(jTFKey.getText()));
        }
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Add numbers only for the key!");
        }
        jLEncodedMessage.setText(e[index].getEncodedMessage());
        jLEncodedMessage2.setText(e[index].getEncodedMessage());
        jBDecode.setEnabled(true);
    }//GEN-LAST:event_jBEncodeActionPerformed

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed

        try {
            e[index].setMessage(jTFMessage.getText(), Integer.parseInt(jTFKey.getText()));
        }
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Add numbers only for the key!");
        }
        saveFile();
    }//GEN-LAST:event_jBSaveActionPerformed

    private void jBRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRandomActionPerformed
        jTFKey.setText(Integer.toString(((int)(Math.random() * 50)) + 1));
        messageCheck();
    }//GEN-LAST:event_jBRandomActionPerformed

    private void jBOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOpenActionPerformed
        jLDecodedMessage.setText("");
        loadFile();
        
        /*The three objects are searched for index from file.
        The decode button will use the correct decoding procedure. 
        */
        for (int i=0; i<3; ++i)
            index = e[i].getIndex();
        
        jLEncodedMessage2.setText(e[index].getEncodedMessage());
        
    }//GEN-LAST:event_jBOpenActionPerformed

    private void jBDecodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDecodeActionPerformed
        
        if (e[index].getEncodedMessage().equals(""))
            jLDecodedMessage.setText("No message!");
        else {
            
            e[index].setEncodedMessage(e[index].getEncodedMessage(), e[index].getKey());
            jLDecodedMessage.setText(e[index].getMessage());
            jBDecode.setEnabled(false);//pressing decode repeatedly caused problems.
        }
    }//GEN-LAST:event_jBDecodeActionPerformed

    private void jRBPrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPrimeActionPerformed
        index = 0;
        e[index].setIndex(index);
        jLDecodedMessage.setText("");
    }//GEN-LAST:event_jRBPrimeActionPerformed

    private void jRBQwertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBQwertyActionPerformed
        index = 1;
        e[index].setIndex(index);
        jLDecodedMessage.setText("");
    }//GEN-LAST:event_jRBQwertyActionPerformed

    private void jRBAlternateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAlternateActionPerformed
        index = 2;
        e[index].setIndex(index);
        jLDecodedMessage.setText("");
    }//GEN-LAST:event_jRBAlternateActionPerformed
    
    private void messageCheck() {
        //Something has to be in both text fields for the encode save and radio buttons to be available.
        if (!jTFMessage.getText().equals("") && !jTFKey.getText().equals("")) {
            jRBPrime.setEnabled(true);
            jRBQwerty.setEnabled(true);
            jRBAlternate.setEnabled(true);
            jBEncode.setEnabled(true);
            jBSave.setEnabled(true);
        }
        else {
            jRBPrime.setEnabled(false);
            jRBQwerty.setEnabled(false);
            jRBAlternate.setEnabled(false);
            jBEncode.setEnabled(false);
            jBSave.setEnabled(false);
        }
    }
    
    private void saveFile(){
        JFileChooser fileChooser = new JFileChooser();
        int choice = fileChooser.showSaveDialog(this);
        if(choice == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            
            e[index].writeFile(file);
        }
    }
    
    private void loadFile(){
        JFileChooser fileChooser = new JFileChooser();
        int choice = fileChooser.showOpenDialog(this);
        if(choice == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            
            //Saving information from file to all three objects.
            for (int i=0; i<3; ++i)
                e[i].readFile(file);
            
            //incase the decode button was disabled.
            jBDecode.setEnabled(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EnigmaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EnigmaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EnigmaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EnigmaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EnigmaFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBDecode;
    private javax.swing.JButton jBEncode;
    private javax.swing.JButton jBOpen;
    private javax.swing.JButton jBRandom;
    private javax.swing.JButton jBSave;
    private javax.swing.JLabel jLDecodedMessage;
    private javax.swing.JLabel jLEncodedMessage;
    private javax.swing.JLabel jLEncodedMessage2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRBAlternate;
    private javax.swing.JRadioButton jRBPrime;
    private javax.swing.JRadioButton jRBQwerty;
    private javax.swing.JTextField jTFKey;
    private javax.swing.JTextField jTFMessage;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}