//Alan Himes
//ahimes1@cnm.edu
//Program 8 - Database Manipulation
//CIS2235
//File: MainP8.java, DbFrame.java, AddPanel.java, UpdatePanel.java, DeletePanel.java, Data.java, DbManager.java

package Data;

/**
 *
 * @author ahimes1
 */
public class Data {
    int id;
    String groceryItem;
    boolean expensive;
    int amount;
    String comments;
    
    public Data() {
        id = 1;//no set method, auto-generated by Access
        groceryItem = "";
        expensive = false;
        amount = 1;
        comments = "";
    }
    
    public Data(String strId, String gi, String exp, String amt, String cmt){
        id = Integer.parseInt(strId);
        groceryItem = gi;
        
        System.out.println(exp);
        
        if (exp.equals("0"))
            expensive = false;
        else
            expensive = true;
        amount = Integer.parseInt(amt);
        comments = cmt;
    }
    
    public void setID(int id) {
        this.id = id;
    }
    
    public void setGroceryItem(String gi){
        groceryItem = gi;
    }
    
    public void setExpensive(boolean exp) {
        expensive = exp;
    }
    
    public void setAmount(int amt) {
        amount = amt;
    }
    
    public void setComments(String cmt) {
        comments = cmt;
    }
    
    public int getID() {
        return id;
    }
    
    public String getGroceryItem() {
        return groceryItem;
    }
    
    public boolean getExpensive() {
        return expensive;
    }
    
    public int getAmount() {
        return amount;
    }
    
    public String getComments() {
        return comments;
    }
}
