<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="StoresWebForm.aspx.cs" Inherits="HimesP6.StoresWebForm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            height: 23px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <h4>Actual stores!</h4>
    
    </div>
        <asp:GridView ID="grvStores" runat="server" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Horizontal" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="sdsStores" DataKeyNames="pkStoresID">
            <Columns>
                <asp:BoundField DataField="pkStoresID" HeaderText="pkStoresID" SortExpression="pkStoresID" InsertVisible="False" ReadOnly="True" />
                <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                <asp:BoundField DataField="address" HeaderText="address" SortExpression="address" />
                <asp:BoundField DataField="phone" HeaderText="phone" SortExpression="phone" />
                <asp:BoundField DataField="city" HeaderText="city" SortExpression="city" />
                <asp:BoundField DataField="state" HeaderText="state" SortExpression="state" />
                <asp:BoundField DataField="zip" HeaderText="zip" SortExpression="zip" />
                <asp:BoundField DataField="hours" HeaderText="hours" SortExpression="hours" />
            </Columns>
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#242121" />
        </asp:GridView>
        <asp:SqlDataSource ID="sdsStores" runat="server" 
            ConnectionString="<%$ ConnectionStrings:StoresConnectionString %>" 
            SelectCommand="SELECT * FROM [stores]" DeleteCommand="DELETE FROM [stores] WHERE [pkStoresID] = @pkStoresID" InsertCommand="INSERT INTO [stores] ([name], [address], [phone], [city], [state], [zip], [hours]) VALUES (@name, @address, @phone, @city, @state, @zip, @hours)" UpdateCommand="UPDATE [stores] SET [name] = @name, [address] = @address, [phone] = @phone, [city] = @city, [state] = @state, [zip] = @zip, [hours] = @hours WHERE [pkStoresID] = @pkStoresID">
            <DeleteParameters>
                <asp:Parameter Name="pkStoresID" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:FormParameter Name="name" FormField="txbName" Type="String" />
                <asp:FormParameter Name="address" FormField="txbAddress" Type="String" />
                <asp:FormParameter Name="phone" FormField="txbPhone" Type="String" />
                <asp:FormParameter Name="city" FormField="txbCity" Type="String" />
                <asp:FormParameter Name="state" FormField="txbState" Type="String" />
                <asp:FormParameter Name="zip" FormField="txbZip" Type="String" />
                <asp:FormParameter Name="hours" FormField="txbHours" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="address" Type="String" />
                <asp:Parameter Name="phone" Type="String" />
                <asp:Parameter Name="city" Type="String" />
                <asp:Parameter Name="state" Type="String" />
                <asp:Parameter Name="zip" Type="String" />
                <asp:Parameter Name="hours" Type="String" />
                <asp:Parameter Name="pkStoresID" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    <table class="auto-style1">
        <tr>
            <td class="auto-style2">Store name</td>
            <td class="auto-style2">
                <asp:TextBox ID="txbName" runat="server" Width="300px"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>Address</td>
            <td>
                <asp:TextBox ID="txbAddress" runat="server" Width="300px"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>Phone #</td>
            <td>
                <asp:TextBox ID="txbPhone" runat="server" Width="300px"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>City</td>
            <td>
                <asp:TextBox ID="txbCity" runat="server" Width="300px"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>State</td>
            <td>
                <asp:TextBox ID="txbState" runat="server" Width="300px"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td class="auto-style2">Zip code</td>
            <td class="auto-style2">
                <asp:TextBox ID="txbZip" runat="server" Width="300px"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>Hours of operation</td>
            <td>
                <asp:TextBox ID="txbHours" runat="server" Width="300px"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>
                <asp:Button ID="btnSubmit" runat="server" OnClick="btnSubmit_Click" Text="Submit" />
                <asp:Button ID="BtnClear" runat="server" OnClick="BtnClear_Click" Text="Clear" />
            </td>
            <td>&nbsp;</td>
        </tr>
    </table>
        <asp:Label ID="lblError" runat="server"></asp:Label>
    </form>
    </body>
</html>
