//Alan Himes
//ahimes1@cnm.edu
//Program 7 - Polygons
//CIS2235
//File: MainP7.java, ControlPanel.java, DrawPanel.java, InfoPanel.java, PolygonCalc.java, PolygonFrame.java

package Program7;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author ahimes1
 */
public class ControlPanel extends javax.swing.JPanel {
    private PolygonFrame frame;
    private Color color;
    
    /**
     * Creates new form ControlPanel
     */
    public ControlPanel(PolygonFrame pf) {
        
        
        frame = pf;
        color = Color.BLACK;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlRadius = new javax.swing.JSlider(jSlRadius.VERTICAL, 1, 10, 1);
        jLRadius = new javax.swing.JLabel();
        jLSides = new javax.swing.JLabel();
        jSpSides = new javax.swing.JSpinner();
        jCCircle = new javax.swing.JCheckBox();
        jBColor = new javax.swing.JButton();

        setBackground(new java.awt.Color(64, 64, 64));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SHAPE CONTROLS", 2, 0, new java.awt.Font("Lucida Grande", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        setPreferredSize(new java.awt.Dimension(150, 500));

        jSlRadius.setMajorTickSpacing(1);
        jSlRadius.setPaintLabels(true);
        jSlRadius.setBackground(new java.awt.Color(64, 64, 64));
        jSlRadius.setForeground(new java.awt.Color(255, 255, 255));
        jSlRadius.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlRadius.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlRadiusStateChanged(evt);
            }
        });

        jLRadius.setForeground(new java.awt.Color(255, 255, 255));
        jLRadius.setText("Radius");

        jLSides.setForeground(new java.awt.Color(255, 255, 255));
        jLSides.setText("Sides");

        jSpSides.setModel(new javax.swing.SpinnerNumberModel(3, 3, 10, 1));
        jSpSides.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpSidesStateChanged(evt);
            }
        });

        jCCircle.setBackground(new java.awt.Color(64, 64, 64));
        jCCircle.setForeground(new java.awt.Color(255, 255, 255));
        jCCircle.setText("Circle");
        jCCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCircleActionPerformed(evt);
            }
        });

        jBColor.setText("Color");
        jBColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBColor)
                    .addComponent(jCCircle)
                    .addComponent(jLSides)
                    .addComponent(jLRadius)
                    .addComponent(jSlRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpSides, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLSides)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpSides, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLRadius)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCCircle)
                .addGap(18, 18, 18)
                .addComponent(jBColor)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBColorActionPerformed
        color = JColorChooser.showDialog(null, "Choose a color.", color);
        frame.setColor(color);
    }//GEN-LAST:event_jBColorActionPerformed

    private void jCCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCircleActionPerformed
        if (jCCircle.isSelected()) {
            frame.circleCheck(true);
            
        }
        else {
            frame.circleCheck(false);
            
        }
    }//GEN-LAST:event_jCCircleActionPerformed

    private void jSpSidesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpSidesStateChanged
        frame.spinnerSelect(Integer.parseInt(jSpSides.getValue().toString()));
        frame.calc();
    }//GEN-LAST:event_jSpSidesStateChanged

    private void jSlRadiusStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlRadiusStateChanged
        frame.sliderSelect(jSlRadius.getValue());
        frame.calc();
    }//GEN-LAST:event_jSlRadiusStateChanged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBColor;
    private javax.swing.JCheckBox jCCircle;
    private javax.swing.JLabel jLRadius;
    private javax.swing.JLabel jLSides;
    private javax.swing.JSlider jSlRadius;
    private javax.swing.JSpinner jSpSides;
    // End of variables declaration//GEN-END:variables
}
