//Alan Himes
//ahimes1@cnm.edu
//Program 7 - Polygons
//CIS2235
//File: MainP7.java, ControlPanel.java, DrawPanel.java, InfoPanel.java, PolygonCalc.java, PolygonFrame.java

package Program7;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author ahimes1
 */
public class PolygonFrame extends javax.swing.JFrame {
    private ControlPanel cp;
    private DrawPanel dp;
    private InfoPanel ip;
    private PolygonCalc pc;
    
    /**
     * Creates new form PolygonFrame
     */
    public PolygonFrame() {
        initComponents();
        cp = new ControlPanel(this);
        dp = new DrawPanel();
        ip = new InfoPanel();
        
        //default constructor values are set to radius = 1, sides = 3
        pc = new PolygonCalc();
        dp.setRadius(1);
        dp.setSides(3);
        
        setLayout(new BorderLayout());
        add(cp, BorderLayout.WEST);
        add(dp, BorderLayout.CENTER);
        add(ip, BorderLayout.EAST);
        
        circleCheck(false);
        
    }

        public void circleCheck(boolean check) {
        
        ip.circleStats(check);
        dp.setCircle(check);
        ip.setCircle(check);
        dp.drawShape();
        
        calc();
    }
    
    public void spinnerSelect(int sides){
        //values come from the spinner and go to PolygonCalc and DrawPanel.
        pc.setNumberSides(sides);
        dp.setSides(sides);
        dp.drawShape();
    }
    
    public void sliderSelect(int radius){
        //values come from the slider and go to PolygonCalc and DrawPanel.
        pc.setRadius(radius);
        dp.setRadius(radius);
        dp.drawShape();
    }
    
    public void calc() {
        ip.setPerimeter(pc.getPerimeter());
        ip.setArea(pc.getPolygonArea());
        ip.setCircumference(pc.getCircumference());
        ip.setCircleArea(pc.getCircleArea());
        dp.drawShape();
        
        //with all the data received and calculated, it's passed to infoPanel.
        ip.measurements();
    }
    
    public void setColor(Color c) {
        //color is set in controlPanel, passed here and sent to DrawPanel.
        dp.setColor(c);
        dp.drawShape();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PolygonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PolygonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PolygonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PolygonFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PolygonFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
