<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EntityDemo.aspx.cs" Inherits="DatabaseDemoStarter.EntityDemo" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:GridView 
            ID="GridView1" 
            runat="server"
            AutoGenerateColumns = "false"
            AutoGenerateEditButton ="true"
            AutoGenerateDeleteButton ="true"
            DataKeyNames ="pkEmployeeID"
            OnRowEditing ="GridView1_RowEditing"
            OnRowUpdating ="GridView1_RowUpdating"
            OnRowCancelingEdit ="GridView1_RowCancelingEdit"
            OnRowDeleting ="GridView1_RowDeleting">
            <Columns>
                <asp:BoundField DataField ="pkEmployeeID"/>
                <asp:BoundField DataField ="Name" />
                <asp:BoundField DataField ="website" />
            </Columns>
        </asp:GridView>
        <p>
            Name:  <asp:TextBox ID="txbName" runat="server"></asp:TextBox>
        </p>
        <p>
            Website: <asp:TextBox ID="txbWebsite" runat="server"></asp:TextBox>
        </p>
        <p>
            <asp:Button ID="btnSubmit" runat="server" Text="Button" OnClick="btnSubmit_Click" />
        </p>

    </div>
    </form>
</body>
</html>
