//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseDemoStarter
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartment
    {
        public int pkDepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> fkDepartmentHeadID { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
