/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package User;

import Data.Data;
import Data.DbManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author ahimes1
 */
public class AddPanel extends javax.swing.JPanel {
    private Data data;
    private DbManager db;
    
    /**
     * Creates new form AddPanel
     */
    public AddPanel() {
        initComponents();
        
        data = new Data();
        db = new DbManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRBYes = new javax.swing.JRadioButton();
        jRBNo = new javax.swing.JRadioButton();
        jLGroceryItem = new javax.swing.JLabel();
        jTFGroceryItem = new javax.swing.JTextField();
        jSlAmount = new javax.swing.JSlider(0, 100, 1);
        jLNumDisplay = new javax.swing.JLabel();
        jBAdd = new javax.swing.JButton();
        jLExpensive = new javax.swing.JLabel();
        jLAmount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTFComments = new javax.swing.JTextField();

        buttonGroup1.add(jRBYes);
        jRBYes.setSelected(true);
        jRBYes.setText("Yes");

        buttonGroup1.add(jRBNo);
        jRBNo.setText("No");

        jLGroceryItem.setText("Grocery Item");

        jSlAmount.setMinorTickSpacing(1);
        jSlAmount.setMajorTickSpacing(10);
        jSlAmount.setPaintLabels(true);
        jSlAmount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlAmountStateChanged(evt);
            }
        });

        jLNumDisplay.setText("1");

        jBAdd.setText("Add to database");
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });

        jLExpensive.setText("Is it expensive?");

        jLAmount.setText("Amount of items:");

        jLabel1.setText("Comments");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBNo)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLNumDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSlAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRBYes, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLAmount, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLExpensive, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLGroceryItem, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTFGroceryItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                    .addComponent(jTFComments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLGroceryItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFGroceryItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLExpensive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBNo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLNumDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFComments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jBAdd)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSlAmountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlAmountStateChanged
        int value = jSlAmount.getValue();
        
        data.setAmount(value);
        jLNumDisplay.setText(Integer.toString(value));
    }//GEN-LAST:event_jSlAmountStateChanged

    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed
        add();
    }//GEN-LAST:event_jBAddActionPerformed
    
    private void add() {
        /*This method sets fields grocery items, expensive and comments.
        The slider sets the amount.
        The most recent ID is obtained and set after the record is added,
        the updated Data object is sent to the Frame which passes it to the 
        other two panels. 
        */
                
        data.setGroceryItem(jTFGroceryItem.getText());
        
        boolean radio;
        if (jRBYes.isSelected())
            radio = true;
        else
            radio = false;
        data.setExpensive(radio);
        
        data.setComments(jTFComments.getText());
        
        try {
            
            db.insert(data);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Failed to add record to database.");
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAdd;
    private javax.swing.JLabel jLAmount;
    private javax.swing.JLabel jLExpensive;
    private javax.swing.JLabel jLGroceryItem;
    private javax.swing.JLabel jLNumDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRBNo;
    private javax.swing.JRadioButton jRBYes;
    private javax.swing.JSlider jSlAmount;
    private javax.swing.JTextField jTFComments;
    private javax.swing.JTextField jTFGroceryItem;
    // End of variables declaration//GEN-END:variables
}
