/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package User;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
//import Data.Data;
/**
 *
 * @author ahimes1
 */
public class DbFrame extends javax.swing.JFrame {

    private AddPanel add;
    private UpdatePanel update;
    private DeletePanel delete;
    //private Data data;
    
    /**
     * Creates new form DbFrame
     */
    public DbFrame() {
        initComponents();

        //add = new AddPanel(this);//might remove the this.
        add = new AddPanel();
        update = new UpdatePanel();
        delete = new DeletePanel();
        //data = new Data();
        
        //Adding panels to layered panes
        jLPAdd.setLayout(new BorderLayout());
        jLPAdd.add(add, BorderLayout.CENTER);
        jLPUpdate.setLayout(new BorderLayout());
        jLPUpdate.add(update, BorderLayout.CENTER);
        jLPDelete.setLayout(new BorderLayout());
        jLPDelete.add(delete, BorderLayout.CENTER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLPAdd = new javax.swing.JLayeredPane();
        jLPUpdate = new javax.swing.JLayeredPane();
        jLPDelete = new javax.swing.JLayeredPane();
        jMenuBarFileHelp = new javax.swing.JMenuBar();
        jMenuFileEdit = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jLPAddLayout = new javax.swing.GroupLayout(jLPAdd);
        jLPAdd.setLayout(jLPAddLayout);
        jLPAddLayout.setHorizontalGroup(
            jLPAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jLPAddLayout.setVerticalGroup(
            jLPAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Add Record", jLPAdd);

        jLPUpdate.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLPUpdateComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLPUpdateComponentShown(evt);
            }
        });
        jLPUpdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLPUpdateFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jLPUpdateLayout = new javax.swing.GroupLayout(jLPUpdate);
        jLPUpdate.setLayout(jLPUpdateLayout);
        jLPUpdateLayout.setHorizontalGroup(
            jLPUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jLPUpdateLayout.setVerticalGroup(
            jLPUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Update Record", jLPUpdate);

        jLPDelete.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLPDeleteComponentShown(evt);
            }
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLPDeleteComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout jLPDeleteLayout = new javax.swing.GroupLayout(jLPDelete);
        jLPDelete.setLayout(jLPDeleteLayout);
        jLPDeleteLayout.setHorizontalGroup(
            jLPDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        jLPDeleteLayout.setVerticalGroup(
            jLPDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Delete Record", jLPDelete);

        jMenuFileEdit.setText("File");
        jMenuFileEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileEditActionPerformed(evt);
            }
        });

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenuFileEdit.add(jMenuExit);

        jMenuBarFileHelp.add(jMenuFileEdit);

        jMenu2.setText("Help");

        jMenuAbout.setText("About");
        jMenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAboutActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuAbout);

        jMenuHelp.setText("Help");
        jMenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHelpActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuHelp);

        jMenuBarFileHelp.add(jMenu2);

        setJMenuBar(jMenuBarFileHelp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        //this didn't work
        
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jLPUpdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLPUpdateFocusLost
        //this neither
    }//GEN-LAST:event_jLPUpdateFocusLost

    private void jLPUpdateComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLPUpdateComponentHidden
        update.deselect();
        //Causes null pointer exception, but program works fine.
        //Without it, an error occurs if something selected in update tab is deleted.
    }//GEN-LAST:event_jLPUpdateComponentHidden

    private void jLPUpdateComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLPUpdateComponentShown
        update.initializeArrays();//Creates the arrays of update's IDs and Items with latest version of database
        //update.setGUI(); this might not be necessary if nothing is clicked. Has been changed back to private.
        //update.setData(update.getData()); this worked as far as I could tell
        update.updateList();
    }//GEN-LAST:event_jLPUpdateComponentShown

    private void jLPDeleteComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLPDeleteComponentHidden
        delete.deselect();
    }//GEN-LAST:event_jLPDeleteComponentHidden

    private void jLPDeleteComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLPDeleteComponentShown
        delete.initializeArrays();
        delete.updateList();
    }//GEN-LAST:event_jLPDeleteComponentShown

    private void jMenuFileEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFileEditActionPerformed
        //wrong
    }//GEN-LAST:event_jMenuFileEditActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jMenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAboutActionPerformed
        JOptionPane.showMessageDialog(null, "The grocery items database.", 
                "About", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_jMenuAboutActionPerformed

    private void jMenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHelpActionPerformed
        JOptionPane.showMessageDialog(null, "Add items on the Add Items tab.\r\n"
                + "Update items on the Update Record Tab.\r\n"
                + "Delete items on the Delete Record tab.\r\nSee HimesP8/Groceries.mdb", 
                "Help", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_jMenuHelpActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DbFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DbFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DbFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DbFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DbFrame().setVisible(true);
//            }
//        });
//    }
    
    /*See if it works with this commented out. 
    */
//    public void setDataOtherPanels(Data d){
//        update.setData(d);
//        delete.setData(d);
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLPAdd;
    private javax.swing.JLayeredPane jLPDelete;
    private javax.swing.JLayeredPane jLPUpdate;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuAbout;
    private javax.swing.JMenuBar jMenuBarFileHelp;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenu jMenuFileEdit;
    private javax.swing.JMenuItem jMenuHelp;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
