/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package User;

import Data.Data;
import Data.DbManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author ahimes1
 */
public class UpdatePanel extends javax.swing.JPanel {
    private Data data;
    private DbManager db;
    private String[] groceries;
    private int[] ids;
    /**
     * Creates new form UpdatePanel
     */
    public UpdatePanel() {
        initComponents();
         
        data = new Data();
        db = new DbManager();
        
        initializeArrays();//Populates String and int arrays with data from table.
        updateList();//List is updated with most recent list of names.
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListGroceries = new javax.swing.JList();
        jLGroceries = new javax.swing.JLabel();
        jRBYes = new javax.swing.JRadioButton();
        jRBNo = new javax.swing.JRadioButton();
        jLGroceryItem = new javax.swing.JLabel();
        jLExpensive = new javax.swing.JLabel();
        jTFGroceryItem = new javax.swing.JTextField();
        jLAmount = new javax.swing.JLabel();
        jSlAmount = new javax.swing.JSlider(0, 100, 1);
        jLabel1 = new javax.swing.JLabel();
        jLNumDisplay = new javax.swing.JLabel();
        jTFComments = new javax.swing.JTextField();
        jBUpdate = new javax.swing.JButton();

        jListGroceries.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListGroceries.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListGroceries.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListGroceriesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListGroceries);

        jLGroceries.setText("Groceries");

        buttonGroup1.add(jRBYes);
        jRBYes.setText("Yes");

        buttonGroup1.add(jRBNo);
        jRBNo.setText("No");

        jLGroceryItem.setText("Grocery Item");

        jLExpensive.setText("Is it expensive?");

        jLAmount.setText("Amount of items:");

        jSlAmount.setMinorTickSpacing(1);
        jSlAmount.setMajorTickSpacing(10);
        jSlAmount.setPaintLabels(true);
        jSlAmount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlAmountStateChanged(evt);
            }
        });

        jLabel1.setText("Comments");

        jLNumDisplay.setText("1");

        jBUpdate.setText("Update field");
        jBUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLGroceries)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBNo)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLNumDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSlAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRBYes, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLAmount, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLExpensive, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLGroceryItem, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFGroceryItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTFComments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBUpdate)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLGroceryItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFGroceryItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLExpensive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBNo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLAmount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLNumDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFComments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLGroceries)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSlAmountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlAmountStateChanged
        int value = jSlAmount.getValue();

        data.setAmount(value);
        jLNumDisplay.setText(Integer.toString(value));
    }//GEN-LAST:event_jSlAmountStateChanged

    private void jListGroceriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListGroceriesValueChanged
        updateDataObj(ids[jListGroceries.getSelectedIndex()]);//Updates data object with database
        setGUI();
    }//GEN-LAST:event_jListGroceriesValueChanged

    private void jBUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpdateActionPerformed
        update();//updates data object with GUI values, which updates the database
        initializeArrays();
        updateList();
    }//GEN-LAST:event_jBUpdateActionPerformed

    //to receive updates from other classes for use
    
    private void update() {
        data.setGroceryItem(jTFGroceryItem.getText());
        
        boolean radio;
        if (jRBYes.isSelected())
            radio = true;
        else
            radio = false;
        data.setExpensive(radio);
        //Again, amount is set with the slider
        data.setComments(jTFComments.getText());
        
        try{
            db.update(data);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Unable to update table data.");
        }
    }
    
    /*The latest arrays of the GROCERYITEMS and ID fields
    are assigned to arrays whenever:
    UpdatePanel's constructor is activated;
    When the Update button is pressed;
    When the Update tab is selected.
    
    UpdateList() is also called during these occasions
    to populate the list with the latest version of the
    String array. 
    
    The Int array is used to find the ID
    corresponding to the list's element, and the ID is used
    to get the selected Data's info to display and update
    (or delete in DeletePanel).
    */
    public void initializeArrays() {
        try {
            groceries = db.getDataList();
            ids = db.getDataID();
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Unable to obtain data.");
        }
    }
    
    public void updateList(){
        jListGroceries.setListData(groceries);
    }
    
    private void updateDataObj(int index){
        //index should correspond to item on list
        
        try {
            data = db.getData(index);
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Unable to obtain data.");
        }
    }
    
    private void setGUI(){
        //sets the panel components to whatever's selected on the list. 
        jTFGroceryItem.setText(data.getGroceryItem());
        if (data.getExpensive()) {
            jRBYes.doClick();
        }
        else if (!data.getExpensive()) {
            jRBNo.doClick();
        }
        
        jSlAmount.setValue(data.getAmount());
        
        jTFComments.setText(data.getComments());
    }
    
    public void deselect() {
        jListGroceries.clearSelection();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBUpdate;
    private javax.swing.JLabel jLAmount;
    private javax.swing.JLabel jLExpensive;
    private javax.swing.JLabel jLGroceries;
    private javax.swing.JLabel jLGroceryItem;
    private javax.swing.JLabel jLNumDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListGroceries;
    private javax.swing.JRadioButton jRBNo;
    private javax.swing.JRadioButton jRBYes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlAmount;
    private javax.swing.JTextField jTFComments;
    private javax.swing.JTextField jTFGroceryItem;
    // End of variables declaration//GEN-END:variables
}
